// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransaction = "transaction"

// Transaction mapped from table <transaction>
type Transaction struct {
	ID        *int64  `gorm:"column:id;type:bigint(20)" json:"id"`
	Hash      *string `gorm:"column:hash;type:varchar(100)" json:"hash"`
	Status    *int64  `gorm:"column:status;type:tinyint(4)" json:"status"`
	UpdatedAt *int64  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedAt *int64  `gorm:"column:created_at;type:int(11)" json:"created_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
