// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVerifier = "verifier"

// Verifier mapped from table <verifier>
type Verifier struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AttestationID string    `gorm:"column:attestation_id;not null" json:"attestation_id"`
	CampaignID    string    `gorm:"column:campaign_id;not null" json:"campaign_id"`
	BlockNumber   int32     `gorm:"column:block_number;not null" json:"block_number"`
	Address       string    `gorm:"column:address;not null" json:"address"`
	TxHash        string    `gorm:"column:tx_hash;not null" json:"tx_hash"`
	Status        string    `gorm:"column:status;not null" json:"status"`
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Verifier's table name
func (*Verifier) TableName() string {
	return TableNameVerifier
}
