package common

const CACHE_EXPIRED_TIME = 10 // Second
const UPDATE_NODE_COMMISSION_RATE_BY_GASLESS_SERVICE = "UpdateNodeCommissionRateByGaslessService"
const UPDATE_NODE_REWARD_CLAIMER_BY_GASLESS_SERVICE = "UpdateNodeRewardClaimerByGaslessService"
const NODE_EXIT_BY_GASLESS_SERVICE = "NodeExitByGaslessService"
const NODE_ENTRY_BY_GASLESS_SERVICE = "NodeEntryByGaslessService"
const NODE_REPORT_VERIFICATION_BATCH_BY_GASLESS_SERVICE = "NodeReportVerificationBatchByGaslessService"
